Updated stats dApp backend selection
webb-tools/webb-dapp pull request #1021
Opened 2023-02-23 14:47 UTC by devpavan04

## Summary of changes

- [ ] Users can switch between testnets and dev endpoints
- [x] Users can switch between different working deployments (Tangle Alpha & Tangle Standalone) in testnets category
- [ ] Users can select local endpoint in dev category
- [ ] Users can add custom endpoint in dev category

### Proposed area of change

- [ ] `apps/bridge-dapp`
- [x] `apps/stats-dapp`
- [ ] `apps/webbsite`
- [ ] `libs/webb-ui-components`

### Reference issue to close (if applicable)

- Closes #1009 

### Screenshots
<img width="237" alt="Screenshot 2023-02-23 at 6 46 21 AM" src="https://user-images.githubusercontent.com/53374218/220940464-b14b0248-2be1-4c5b-89c8-fc8b79b03d68.png">
<img width="249" alt="Screenshot 2023-02-23 at 6 46 30 AM" src="https://user-images.githubusercontent.com/53374218/220940474-a37e736c-31f0-4d0e-980c-f6be7adc792b.png">

-----
### Code Checklist 
_Please be sure to add .stories documentation if any additions are made to `libs/webb-ui-components`._

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2023-02-23 21:36 UTC, dutterbutter commented
@devpavan04 I updated this PR to resolve build / format issue. I tested the Alpha and Standalone buttons work well but the 'DEV' inputs do not seem to work as intended. I have created scripts in this PR: https://github.com/webb-tools/webb-subql/pull/51 that automates the local setup of standalone tangle network that you can test the backend against.

2023-02-24 15:15 UTC, dutterbutter commented
@devpavan04 we are deprecating the parachain network (e.g. Tangle Alpha) so please remove its reference in this PR. The changes I introduced in #1022 removes it from previous setup.

2023-03-01 20:45 UTC, dutterbutter approved these changes
LGTM but I will wait to merge for @AtelyPham to review.

2023-03-02 13:07 UTC, AtelyPham commented on libs/icons/src/DeleteBinWithBg.tsx
> +      <svg viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
The `createIcon` function already creates an `<svg></svg>` wrapper, so that you won't need the svg wrapper here.

2023-03-02 13:07 UTC, AtelyPham commented on libs/icons/src/Save.tsx
> +      <svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
Consider removing svg element here too.

2023-03-02 13:07 UTC, AtelyPham commented on libs/icons/src/SaveWithBg.tsx
> +      <svg viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
Consider removing svg element here too.

2023-03-02 13:08 UTC, AtelyPham commented on libs/icons/src/TangleIcon.tsx
> +      <svg viewBox="0 0 32 28" fill="none" xmlns="http://www.w3.org/2000/svg">
Consider removing svg element here too.

2023-03-02 13:08 UTC, AtelyPham commented on libs/logos/src/chains/TangleLogo.tsx
> +    <svg viewBox="0 0 32 28" fill="none" xmlns="http://www.w3.org/2000/svg">
Consider removing svg element here too.

2023-03-02 13:08 UTC, AtelyPham commented on libs/logos/src/chains/TangleLogo.tsx
> +//             d="M32 21.9598C32.0014 20.3605 31.2756 18.8261 29.9819 17.6934C28.6881 16.5606 26.9322 15.9221 25.0994 15.918L17.4484 15.918C17.4003 15.2958 17.37 14.6596 17.37 14C17.37 13.3404 17.339
Please remove unused code.

2023-03-02 13:11 UTC, AtelyPham requested changes
The icon colors look incorrect in light mode. @devpavan04 

<img width="255" alt="CleanShot 2023-03-02 at 19 53 09@2x" src="https://user-images.githubusercontent.com/60747384/222437818-6d75ecd6-7f40-45af-a003-92b404e5c0bc.png">
<img width="262" alt="CleanShot 2023-03-02 at 19 52 59@2x" src="https://user-images.githubusercontent.com/60747384/222437864-690b88e3-69fe-4e28-8aed-7616e615ac26.png">

2023-03-02 20:44 UTC, devpavan04 commented
@AtelyPham @dutterbutter Icons have been updated.

<img width="210" alt="Screenshot 2023-03-02 at 12 31 43 PM" src="https://user-images.githubusercontent.com/53374218/222547469-116da85f-6c08-4531-ad2c-724f8663e525.png">
<img width="210" alt="Screenshot 2023-03-02 at 12 31 51 PM" src="https://user-images.githubusercontent.com/53374218/222547474-c09bb08b-5a70-4c2f-9134-e675a994d81a.png">

<img width="214" alt="Screenshot 2023-03-02 at 12 31 08 PM" src="https://user-images.githubusercontent.com/53374218/222547554-4789e658-1bd9-4d1f-b776-1f2e47bcefef.png">
<img width="210" alt="Screenshot 2023-03-02 at 12 31 19 PM" src="https://user-images.githubusercontent.com/53374218/222547556-22e53f27-5dfd-47df-b311-43bd3ba6368d.png">

2023-03-02 21:13 UTC, merged