Tuan linh/tangle website header
webb-tools/webb-dapp pull request #1073
Opened 2023-03-24 02:36 UTC by vutuanlinh2k2

## Summary of changes
_Provide a detailed description of proposed changes._
- Adding the header for the Tangle Website (Desktop, Tablet and Mobile)

### Proposed area of change
_Put an `x` in the boxes that apply._

- [ ] `apps/bridge-dapp`
- [ ] `apps/stats-dapp`
- [ ] `apps/webbsite`
- [x] `apps/tangle-website`
- [ ] `libs/webb-ui-components`

### Reference issue to close (if applicable)
_Specify any issues that can be closed from these changes (e.g. Closes #233)._
- Closes 

### Screen Recording
_If possible provide a screen recording of proposed change._

https://user-images.githubusercontent.com/69841784/227409616-83b8c6a9-2321-45ab-88ad-dad552a1a5cb.mov

-----
### Code Checklist 
_Please be sure to add .stories documentation if any additions are made to `libs/webb-ui-components`._

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2023-03-24 18:59 UTC, devpavan04 submitted a review, later dismissed
@vutuanlinh2k2 I would suggest moving `TangleLogo` into `webb-ui-components` but LGTM 👍🏼

2023-03-26 04:11 UTC, vutuanlinh2k2 commented on apps/tangle-website/src/components/TangleLogo.tsx
> +export const TangleLogo: React.FC<LogoProps> = (props) => {
@devpavan04 I have pushed the the modify code that move TangleLogo component to the webb-ui-components as you suggested!

2023-03-26 09:47 UTC, AtelyPham requested changes
Please consider removing copying files, fonts @vutuanlinh2k2. Taking a look on the [`develop`](https://github.com/webb-tools/webb-dapp/tree/develop/apps/tangle-website) branch, we should only add necessary files for the tangle.

2023-03-27 08:32 UTC, AtelyPham reviewed
Files and directories to remove:

- `public/fonts` (consider moving supported fonts into `webb-ui-kit`)
- `public/static/assets/community-texture.png`
- `constants/index.ts` (consider moving the `constants` to the `dapp-config` lib for sharing)
- `libs/notion` (we don't need this at this time)

For the headings and subheadings, if you want to share between `webbsite` app and `tangle-website`, please consider moving them into the `webb-ui-kit`. @vutuanlinh2k2

2023-03-28 20:00 UTC, AtelyPham reviewed
Great job on this PR! Just one quick thing - could you please switch out all the fonts here with the default one and make sure to remove them from the tailwind.config.js and global.css files too? We can always import the fonts in a later PR. Thank you.

2023-03-29 07:25 UTC, AtelyPham approved these changes
LGTM 👍

2023-03-29 07:25 UTC, merged