Webbsite Shielded Pool Protocols page
webb-tools/webb-dapp pull request #1335
Opened 2023-06-12 14:25 UTC by vutuanlinh2k2

## Summary of changes
_Provide a detailed description of proposed changes._
- Shielded Pool Protocols pages for the Webbsite

### Proposed area of change
_Put an `x` in the boxes that apply._

- [ ] `apps/bridge-dapp`
- [ ] `apps/stats-dapp`
- [x] `apps/webbsite`
- [ ] `apps/faucet`
- [ ] `apps/tangle-website`
- [ ] `libs/webb-ui-components`

### Reference issue to close (if applicable)
_Specify any issues that can be closed from these changes (e.g. Closes #233)._
- Closes #847 

### Screen Recording
_If possible provide a screen recording of proposed change._

https://github.com/webb-tools/webb-dapp/assets/69841784/9adf1230-6efa-4bcb-a0c4-315b4a11f1eb

### Code Checklist 
_Please be sure to add .stories documentation if any additions are made to `libs/webb-ui-components`._

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2023-06-12 16:15 UTC, devpavan04 requested changes

2023-06-12 17:15 UTC, drewstone commented on apps/webbsite/src/components/shielded-pool/ShieldedPoolExtensionsSection.tsx
> +          protocols. Collaborate wih us to help build extensions, ro get started
@devpavan04 in the future please use the direct edit button for comments like this. Be proactive and fix them yourself to speed things up.
```suggestion
          protocols. Collaborate with us to help build extensions. To get started
```

2023-06-12 19:08 UTC, drewstone requested changes

2023-06-12 19:08 UTC, drewstone commented on apps/webbsite/src/components/shielded-pool/ShieldedPoolExtensionsSection.tsx
> +          started building with them,
@devpavan04 can you fix this too, what's the copy for this supposed to be @thomivy/

"To get started building with them," sounds cut off from the full message?

2023-06-13 02:14 UTC, merged

2023-06-13 02:14 UTC, drewstone commented
Great work @vutuanlinh2k2 and thank you @devpavan04 for jumping in to help!