'Connect Wallet' button instead of empty account
webb-tools/webb-dapp pull request #134
Opened 2021-08-02 15:15 UTC by nepoche

2021-08-03 00:34 UTC, AhmedKorim commented
@nepoche  ,The button for adding custom EVM RPC isn't working anymore

2021-08-03 15:02 UTC, nepoche commented
Just attempted on this branch to add 'Harmony Testnet Shard 1' custom EVM RPC. It seemed to work fine for me.

2021-08-06 22:15 UTC, AhmedKorim commented
This seems not to work for me
- Network switching throw MetaMask doesn’t do anything
- dApp connection never done just keeps showing connecting

2021-08-06 22:39 UTC, AhmedKorim requested changes
Looks good need just a small refactor for the `configureSelectedWallets`

2021-08-06 22:39 UTC, AhmedKorim commented on packages/ui-components/src/Inputs/WalletSelect/ConnectWalletButton.tsx
> +      );
This is used as well on the `WalletSelect.tsx` can we share logic between both places @nepoche

2021-08-17 21:40 UTC, drewstone commented
@AhmedKorim is this ready to be merged or do you still have to review? If it's too stale can we close this?

2021-08-20 15:01 UTC, nepoche commented
I would suggest merging this in because it has a bugfix regarding targeting of chains, or I can split this out in a separate PR: https://github.com/webb-tools/webb-dapp/pull/134/files#diff-c688cc440af23b5cb634e02d91c0efbc31ac3a7fe4dc0dc982ecf18417783af4R26

2021-08-20 17:34 UTC, AhmedKorim commented
Looks good!

2021-08-20 17:34 UTC, merged