Create Tangle Dapp - EVM Staking App
webb-tools/webb-dapp pull request #1777
Opened 2023-10-17 17:05 UTC by devpavan04

## Summary of changes

- Creates a new NextJS app called `tangle-dapp` for `EVM Staking App`

### Reference issue to close (if applicable)

- Closes #1776

2023-10-17 20:18 UTC, AtelyPham reviewed
Left a comment.

2023-10-17 20:18 UTC, AtelyPham commented on apps/tangle-dapp/app/layout.tsx
> +export const revalidate = 5;
Please consider removing this, as it is not needed at the moment.

2023-10-17 20:18 UTC, AtelyPham commented
The CI is failing, @devpavan04!

2023-10-18 01:49 UTC, vutuanlinh2k2 reviewed
Left some comments!

2023-10-18 01:49 UTC, vutuanlinh2k2 commented on apps/tangle-dapp/app/providers.tsx
I already move the next theme provider [here](https://github.com/webb-tools/webb-dapp/blob/develop/libs/api-provider-environment/src/NextThemeProvider.tsx) to reuse it across dapps

2023-10-18 01:49 UTC, vutuanlinh2k2 commented on apps/tangle-dapp/components/sideBar/sideBarActions.ts
consider moving this into the **lib** folder

2023-10-18 16:26 UTC, drewstone approved these changes

2023-10-18 19:42 UTC, AtelyPham requested changes
Please revert some relative imports. Always use the library import @webb-tools/*. If you import from another library, avoid using relative paths.

2023-10-18 19:42 UTC, AtelyPham commented on libs/webb-ui-components/src/components/ChainChip/types.ts
Please revert this. Always use the library import `@webb-tools/*`. If you import from another library, avoid using relative paths.

2023-10-18 19:42 UTC, AtelyPham commented on libs/webb-ui-components/src/components/ChainChip/utils.ts
Please revert this. Always use the library import `@webb-tools/*`. If you import from another library, avoid using relative paths.

2023-10-18 19:42 UTC, AtelyPham commented on libs/webb-ui-components/src/components/WalletConnectionCard/WalletConnectionCard.tsx
Same here

2023-10-18 19:42 UTC, AtelyPham commented on libs/webb-ui-components/src/components/WalletConnectionCard/types.ts
Same here.

2023-10-18 19:42 UTC, AtelyPham commented on libs/webb-ui-components/src/components/buttons/types.ts
Same here.

2023-10-18 19:42 UTC, AtelyPham commented on libs/webb-ui-components/src/containers/ConfirmationCard/types.ts
Same here.

2023-10-18 20:23 UTC, AtelyPham approved these changes

2023-10-18 20:24 UTC, merged