Governance Page components
webb-tools/webb-dapp pull request #1862
Opened 2023-11-29 10:47 UTC by vutuanlinh2k2

## Summary of changes

_Provide a detailed description of proposed changes._

- Implement 2 components for Governance Page: GovernanceContractListingCard and GovernanceContractDetailCard

### Proposed area of change

_Put an `x` in the boxes that apply._

- [ ] `apps/bridge-dapp`
- [ ] `apps/hubble-stats`
- [ ] `apps/stats-dapp`
- [ ] `apps/tangle-dapp`
- [ ] `apps/testnet-leaderboard`
- [ ] `apps/faucet`
- [x] `libs/webb-ui-components`

### Reference issue to close (if applicable)

_Specify any issues that can be closed from these changes (e.g. Closes #233)._

- Closes #1851

### Screen Recording

_If possible provide a screen recording of proposed change._

https://github.com/webb-tools/webb-dapp/assets/69841784/a8d72831-86c1-4e65-8b61-d43d78d2f80c

---

### Code Checklist

_Please be sure to add .stories documentation if any additions are made to `libs/webb-ui-components`._

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2023-11-29 18:56 UTC, drewstone requested changes
Looks good besides small nit. The flow is a bit clearer in my head. I think we will
1. Search contracts (they should exist on all chains a bridge exists on)
2. Click contract of interest (paired with the address of the given contract instance)
3. See governance functions
4. Execute governance function -> if chain wasn't selected from the diagram throw a toast error.
5. Otherwise switch chains if needed and execute on the selected chain at that contract address.

2023-11-29 18:56 UTC, drewstone commented on libs/webb-ui-components/src/components/ListCard/ContractListCard.tsx
> +            placeholder="Search chains"
I think it's not correct to "Search chains", rather it should be searching contracts. Remember that all the contracts that can be governed exist on all the chains.

2023-11-29 18:56 UTC, drewstone commented on libs/webb-ui-components/src/components/ListCard/ContractListCard.tsx
> +            placeholder="Search chains"
```suggestion
            placeholder="Search contracts"
```

2023-11-29 18:56 UTC, drewstone commented on libs/webb-ui-components/src/components/ListCard/ContractListCard.tsx
> +            id="chain"
The `id` should also be updated to `contracts` right?

2023-11-29 18:56 UTC, drewstone commented
This looks good to ship once we address the semantic error between search chains/contracts. If the flow seems correct that's good enough for now @vutuanlinh2k2.

2023-11-30 02:48 UTC, vutuanlinh2k2 commented
> Looks good besides small nit. The flow is a bit clearer in my head. I think we will
> 
> 1. Search contracts (they should exist on all chains a bridge exists on)
> 2. Click contract of interest (paired with the address of the given contract instance)
> 3. See governance functions
> 4. Execute governance function -> if chain wasn't selected from the diagram throw a toast error.
> 5. Otherwise switch chains if needed and execute on the selected chain at that contract address.

I will move the chain ring to the detail card!

2023-11-30 17:28 UTC, merged