EVM Staking - Nomination Flow, Bond More & Change Reward Destination
webb-tools/webb-dapp pull request #1887
Opened 2023-12-08 10:59 UTC by devpavan04

## Summary of changes

- Adds inital `Nomination` flow.
- Adds `Bond More` tokens flow.
- Adds `Change Reward Destination` flow.

### Proposed area of change

- [ ] `apps/bridge-dapp`
- [ ] `apps/hubble-stats`
- [ ] `apps/stats-dapp`
- [x] `apps/tangle-dapp`
- [ ] `apps/testnet-leaderboard`
- [ ] `apps/faucet`
- [x] `libs/webb-ui-components`

### First-Time Nominator Flow: Bond Tokens, Select Reward Destination, and Nominate Validators.

https://github.com/webb-tools/webb-dapp/assets/53374218/620f27a9-4dcf-4a29-ac6f-325f7f2215d2

### Non-First-Time Nominator Flow: Overwrite Nominations Without Bonding More Tokens, Change Reward Destination, and Bond More Tokens.

https://github.com/webb-tools/webb-dapp/assets/53374218/ca4efc01-87bb-45e5-9dbc-4b1f68ad0377

2023-12-11 18:56 UTC, drewstone requested changes
This looks good and the videos are good but we can definitely work to improve code quality. I think you're hugging `try/catch` too aggressively unless you think otherwise (I may be wrong here!).

I see try/catches everywhere however. In the API function calls, in the hooks that use them, and then in the effects/etc. We really only need try/catches at the top level so we can catch and show notification toasts. Otherwise, we should consider letting the awaits fail as usual, especially if they throw their own errors. We would be catching them at the outermost code and try/catch.

2023-12-11 18:56 UTC, drewstone commented on apps/tangle-dapp/containers/DelegateTxContainer/DelegateTxContainer.tsx
> +          if (bondTxHash) {
This is a tremendous amount of nesting and very unclean/unreadable. Can you rework this? We should try to reduce the length of this logic in place of helper functions and less nesting.

2023-12-11 18:56 UTC, drewstone commented on apps/tangle-dapp/containers/DelegateTxContainer/DelegateTxContainer.tsx
> +      if (isFirstTimeNominator) {
Lots of nesting from here. We should keep it to a max of like 2 nested conditionals if possible.

2023-12-11 18:56 UTC, drewstone commented on apps/tangle-dapp/containers/UpdatePayeeTxContainer/UpdatePayeeTxContainer.tsx
> +      if (updatePaymentDestinationTxHash) {
If we used the reverse would it reduce our nesting?
```
if (!updatePaymentDestinationTxHash) { // return or handle when doesn't exist }

const updatePaymentDestinationTx = await evmPublicClient.waitForTransactionReceipt({
	hash: updatePaymentDestinationTxHash,
});
...
```

2023-12-11 18:56 UTC, drewstone commented on apps/tangle-dapp/data/NominatorStats/usePaymentDestinationSubscription.ts
> +          throw WebbError.from(WebbErrorCodes.ApiNotReady);
We're throwing this but do we catch it when this hook is used? Why do we need this try/catch here then? You're kinda using try/catches everywhere but that's making the code even more unclean.

2023-12-14 16:37 UTC, devpavan04 commented
@monaiuu Added search bar.

https://github.com/webb-tools/webb-dapp/assets/53374218/e9e8b4a3-ba44-4541-89a1-e0c393b189af

2023-12-14 16:43 UTC, merged