Fix `zk-explorer` deployment failing on Netlify
webb-tools/webb-dapp pull request #1908
Opened 2023-12-20 20:36 UTC by yurixander

## Summary of changes

_Provide a detailed description of proposed changes._

- A `public` folder is required, otherwise the build fails.
- Added an empty public folder, using `.gitkeep` to be able to stage it into a commit.

### Proposed area of change

_Put an `x` in the boxes that apply._

- [ ] `apps/bridge-dapp`
- [ ] `apps/hubble-stats`
- [ ] `apps/stats-dapp`
- [ ] `apps/tangle-dapp`
- [ ] `apps/testnet-leaderboard`
- [ ] `apps/faucet`
- [x] `apps/zk-explorer`
- [ ] `libs/webb-ui-components`

---

### Code Checklist

_Please be sure to add .stories documentation if any additions are made to `libs/webb-ui-components`._

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2023-12-20 20:49 UTC, yurixander commented
The Netlify deployment logs seems to be complaining of memory exhaustion now, instead of the missing `public` folder (which is the error I was getting locally). However, the other dapps seem to be build properly, so that suggests that it is an issue specifically regarding `zk-explorer`.

2023-12-20 21:24 UTC, yurixander commented
I've increased the Node.js memory limit via `NODE_OPTIONS=--max_old_space_size=4096`, and the memory exhaustion error is gone. This is also present in the Netlify configuration of other dapps, such as `hubble-stats`.

The [deployment is now successful on Netlify](https://deploy-preview-1908--zkexplorer.netlify.app/).

2023-12-20 22:01 UTC, drewstone commented
Looks good, there's a bit of a flash from light/dark theme immediately onload. That should get fixed up. Does this happen to you @yurixander ?

2023-12-20 22:02 UTC, yurixander commented
> Looks good, there's a bit of a flash from light/dark theme immediately onload. That should get fixed up. Does this happen to you @yurixander ?

Yes it does happen to me! When I first started working on the application, there was a warning from Next.js about it, so I thought it was a side effect of Next.js non-production builds or something along those lines. I'll look into it more in detail to find what's the problem.

2023-12-21 06:38 UTC, vutuanlinh2k2 commented on apps/zk-explorer/components/GitHubOAuthButton/GitHubOAuthButton.tsx
>    const handleClick: MouseEventHandler<HTMLButtonElement> = (e) => {
update this to UseCallback function

2023-12-21 06:39 UTC, vutuanlinh2k2 requested changes
After changing this you can merge to the `develop` branch right away @yurixander

2023-12-21 06:50 UTC, merged