EVM Staking - Nomination Update Flow & UI Changes
webb-tools/webb-dapp pull request #1912
Opened 2023-12-27 15:27 UTC by devpavan04

## Summary of changes

- Added a type for `0x${string}` in `dapp-config` as pointed out by @vutuanlinh2k2 in previous PR review.
- Moved `Nomination Update Flow` and `Change Reward Destination Flow` to `Manage` dropdown options of `Nominations` table.
- Added `commission` display in `nominations`, `active`, `waiting` and `validator selection` tables.
- Already nominated validators are pre-selected when users try to update their nominations.
- Users can filter validators by their `commission` when selecting validators to nominate.

### Proposed area of change

- [ ] `apps/bridge-dapp`
- [ ] `apps/hubble-stats`
- [ ] `apps/stats-dapp`
- [x] `apps/tangle-dapp`
- [ ] `apps/testnet-leaderboard`
- [ ] `apps/faucet`
- [ ] `libs/webb-ui-components`

### Reference issue to close (if applicable)

- Closes #1896 
- Closes #1910 

### Screen Recording

https://github.com/webb-tools/webb-dapp/assets/53374218/2391966f-26b7-48da-b553-1922e14e038e

2023-12-28 04:38 UTC, vutuanlinh2k2 approved these changes

2023-12-28 04:38 UTC, vutuanlinh2k2 commented
Added @monaiuu to review flows and UI

2023-12-28 23:37 UTC, monaiuu requested changes
- [x] place `sidenav` component behind `overlay`

![Screenshot 2023-12-28 at 3 35 56 PM](https://github.com/webb-tools/webb-dapp/assets/109539270/6202b04a-13e7-4e33-994b-c68fcafd39e1)

2024-01-01 22:31 UTC, devpavan04 commented
@monaiuu 

![CleanShot 2024-01-01 at 14 29 55](https://github.com/webb-tools/webb-dapp/assets/53374218/e43ad775-fde7-4369-b3e1-ee4fd0430ef4)

2024-01-01 22:32 UTC, merged