chore: remove redundant chains
webb-tools/webb-dapp pull request #1969
Opened 2024-01-19 10:03 UTC by vutuanlinh2k2

## Summary of changes

_Provide a detailed description of proposed changes._

-

### Proposed area of change

_Put an `x` in the boxes that apply._

- [x] `apps/bridge-dapp`
- [x] `apps/hubble-stats`
- [ ] `apps/stats-dapp`
- [x] `apps/tangle-dapp`
- [x] `apps/testnet-leaderboard`
- [x] `apps/faucet`
- [ ] `apps/zk-explorer`
- [x] `libs/webb-ui-components`

### Reference issue to close (if applicable)

_Specify any issues that can be closed from these changes (e.g. `Closes #233`)._

- Closes #1968 

### Code Checklist

_Please be sure to add .stories documentation if any additions are made to `libs/webb-ui-components`._

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2024-01-19 14:40 UTC, AtelyPham commented on libs/dapp-types/src/SubstrateChainId.ts
> +  TangleTestnetNative = 1081, // Live Tangle Native Testnet
We should remove one of these two enum values since they share the same value.

2024-01-19 14:40 UTC, AtelyPham requested changes
Left a comment.

2024-01-21 14:06 UTC, yurixander approved these changes

2024-01-21 20:40 UTC, drewstone commented
Merge conflicts here and then good to go

2024-01-22 14:01 UTC, AtelyPham approved these changes

2024-01-22 14:01 UTC, merged