Active Services table on Services Dashboard page
webb-tools/webb-dapp pull request #2032
Opened 2024-02-15 10:48 UTC by vutuanlinh2k2

## Summary of changes

_Provide a detailed description of proposed changes._

- Active Services table on Services Dashboard page
- Reorder files & refactor code related to Service Tables

### Proposed area of change

_Put an `x` in the boxes that apply._

- [ ] `apps/bridge-dapp`
- [ ] `apps/hubble-stats`
- [ ] `apps/stats-dapp`
- [x] `apps/tangle-dapp`
- [ ] `apps/testnet-leaderboard`
- [ ] `apps/faucet`
- [ ] `apps/zk-explorer`
- [ ] `libs/webb-ui-components`

### Reference issue to close (if applicable)

_Specify any issues that can be closed from these changes (e.g. `Closes #233`)._

- Closes #2031 

### Screen Recording

_If possible provide a screen recording of proposed change._

https://github.com/webb-tools/webb-dapp/assets/69841784/453ba314-a614-49ff-b90c-f4855a2d1096

---

### Code Checklist

_Please be sure to add .stories documentation if any additions are made to `libs/webb-ui-components`._

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2024-02-16 02:36 UTC, yurixander approved these changes

2024-02-16 16:46 UTC, yurixander requested changes
Minor change

2024-02-16 16:46 UTC, yurixander commented on apps/tangle-dapp/components/ServicesKeyMetricItem/ServicesKeyMetricItem.tsx
> +      className={cx(
I'm not sure if cx will handle Tailwind class name conflicts, I think we should be using twMerge here.

2024-02-16 18:00 UTC, monaiuu approved these changes

2024-02-17 05:04 UTC, yurixander approved these changes

2024-02-17 06:49 UTC, merged