feat(leaderboard): Add embed path
webb-tools/webb-dapp pull request #2039
Opened 2024-02-19 01:01 UTC by yurixander

## Summary of changes

_Provide a detailed description of proposed changes._

-

### Proposed area of change

_Put an `x` in the boxes that apply._

- [ ] `apps/bridge-dapp`
- [ ] `apps/hubble-stats`
- [ ] `apps/stats-dapp`
- [ ] `apps/tangle-dapp`
- [x] `apps/testnet-leaderboard`
- [ ] `apps/faucet`
- [ ] `apps/zk-explorer`
- [ ] `libs/webb-ui-components`

### Reference issue to close (if applicable)

_Specify any issues that can be closed from these changes (e.g. `Closes #233`)._

- Closes #1866

### Screen Recording

_If possible provide a screen recording of proposed change._

---

### Code Checklist

_Please be sure to add .stories documentation if any additions are made to `libs/webb-ui-components`._

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2024-02-21 22:02 UTC, monaiuu requested changes
can we slightly increase the space on top within the iframe? (search bar outline is slightly cropped shown below)

<img width="1073" alt="Screenshot 2024-02-21 at 2 01 26 PM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/9b4865b2-c0e3-4145-963b-e513d97de16d">

2024-02-22 00:46 UTC, yurixander commented
Note on the failing check: I fixed the broken link on #2049.

2024-02-22 12:13 UTC, vutuanlinh2k2 approved these changes

2024-02-22 14:34 UTC, AtelyPham approved these changes

2024-02-22 16:12 UTC, merged