Role Distribution on Service Dashboard page
webb-tools/webb-dapp pull request #2052
Opened 2024-02-23 10:40 UTC by vutuanlinh2k2

## Summary of changes

_Provide a detailed description of proposed changes._

- Role Distribution on Service Dashboard page 

### Proposed area of change

_Put an `x` in the boxes that apply._

- [ ] `apps/bridge-dapp`
- [ ] `apps/hubble-stats`
- [ ] `apps/stats-dapp`
- [x] `apps/tangle-dapp`
- [ ] `apps/testnet-leaderboard`
- [ ] `apps/faucet`
- [ ] `apps/zk-explorer`
- [ ] `libs/webb-ui-components`

### Reference issue to close (if applicable)

_Specify any issues that can be closed from these changes (e.g. `Closes #233`)._

- Closes #1982 

### Screen Recording

_If possible provide a screen recording of proposed change._

https://github.com/webb-tools/webb-dapp/assets/69841784/c812116c-84c8-473b-aaff-cd9e0ec81ace

---

### Code Checklist

_Please be sure to add .stories documentation if any additions are made to `libs/webb-ui-components`._

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2024-02-23 15:35 UTC, AtelyPham approved these changes
LGTM 👍

2024-02-23 17:35 UTC, yurixander approved these changes

2024-02-23 19:32 UTC, monaiuu requested changes
Could we add `stroke="none"` to get recharts remove stroke (outline) around each slice of the pie chart?

2024-02-25 01:26 UTC, yurixander approved these changes

2024-02-26 06:40 UTC, merged