What is Restaking Card on Service Dashboard
webb-tools/webb-dapp pull request #2061
Opened 2024-02-27 14:05 UTC by vutuanlinh2k2

## Summary of changes

_Provide a detailed description of proposed changes._

- What is Restaking Card on Service Dashboard
- Minor css modifications for charts
- @monaiuu hide the "What is Restaking" button for now since the page is [not available yet] (https://github.com/webb-tools/tangle-docs/issues/6#issuecomment-1961850580)

### Proposed area of change

_Put an `x` in the boxes that apply._

- [ ] `apps/bridge-dapp`
- [ ] `apps/hubble-stats`
- [ ] `apps/stats-dapp`
- [x] `apps/tangle-dapp`
- [ ] `apps/testnet-leaderboard`
- [ ] `apps/faucet`
- [ ] `apps/zk-explorer`
- [ ] `libs/webb-ui-components`

### Reference issue to close (if applicable)

_Specify any issues that can be closed from these changes (e.g. `Closes #233`)._

- Closes #2060 
- Closes #1975 

### Screen Recording

_If possible provide a screen recording of proposed change._

https://github.com/webb-tools/webb-dapp/assets/69841784/8be020a6-4762-48f6-84ce-338dbca2953b

---

### Code Checklist

_Please be sure to add .stories documentation if any additions are made to `libs/webb-ui-components`._

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2024-02-27 17:45 UTC, AtelyPham approved these changes
LGTM 👍

2024-02-27 18:26 UTC, yurixander requested changes

2024-02-27 23:32 UTC, monaiuu approved these changes

2024-02-28 01:16 UTC, vutuanlinh2k2 commented on apps/tangle-dapp/app/services/WhatIsRestakingCard.tsx
> +        <Link href="/restake">
> Maybe prefer using page url enum in case we refactor the url in the future

Fixed!

2024-02-28 01:32 UTC, merged