fix(tangle-dapp): Pre-launch account page audit
webb-tools/webb-dapp pull request #2145
Opened 2024-03-27 02:57 UTC by yurixander

## Summary of changes

_Provide a detailed description of proposed changes._

-

### Proposed area of change

_Put an `x` in the boxes that apply._

- [ ] `apps/bridge-dapp`
- [ ] `apps/hubble-stats`
- [ ] `apps/stats-dapp`
- [x] `apps/tangle-dapp`
- [ ] `apps/testnet-leaderboard`
- [ ] `apps/faucet`
- [ ] `apps/zk-explorer`
- [ ] `libs/webb-ui-components`

### Reference issue to close (if applicable)

_Specify any issues that can be closed from these changes (e.g. `Closes #233`)._

- Closes

### Screen Recording

_If possible provide a screen recording of proposed change._

---

### Code Checklist

_Please be sure to add .stories documentation if any additions are made to `libs/webb-ui-components`._

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2024-03-27 04:50 UTC, vutuanlinh2k2 commented on apps/tangle-dapp/containers/BalancesTableContainer/LockedBalanceDetails/LockedBalanceDetails.tsx
There's a lot of state being used in this file, I think it's the best if we use `useMemo` in all of the defined variable here

2024-03-27 04:50 UTC, vutuanlinh2k2 reviewed
Left a comment, otherwise LGTM!

2024-03-27 16:36 UTC, monaiuu requested changes
- [ ] Remove avatar display next to address w/o wallet connection:
<img width="443" alt="Screenshot 2024-03-27 at 9 28 54 AM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/a99c9918-c308-4e1a-92f2-6197910d178e">
- [ ] Can remove the component altogether or use below as reference:
<img width="871" alt="Screenshot 2024-03-27 at 9 25 30 AM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/782bcf9d-e988-4a8e-8413-d71925e7da95">

<img width="789" alt="Screenshot 2024-03-27 at 9 26 25 AM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/56fab4c4-cc0b-47bb-8f86-d39b562a8b01">

2024-03-28 01:16 UTC, vutuanlinh2k2 approved these changes

2024-03-28 03:04 UTC, merged