chore: add ExternalLinkIcon component in webb-ui-components
webb-tools/webb-dapp pull request #2238
Opened 2024-04-16 10:28 UTC by vutuanlinh2k2

## Summary of changes

_Provide a detailed description of proposed changes._

- Fetch data for Validator Card component
- Handling loading state 
- Add `ExternalLinkIcon` component in `webb-ui-components`

### Proposed area of change

_Put an `x` in the boxes that apply._

- [ ] `apps/bridge-dapp`
- [ ] `apps/hubble-stats`
- [ ] `apps/stats-dapp`
- [x] `apps/tangle-dapp`
- [ ] `apps/testnet-leaderboard`
- [ ] `apps/faucet`
- [ ] `apps/zk-explorer`
- [x] `libs/webb-ui-components`

### Reference issue to close (if applicable)

_Specify any issues that can be closed from these changes (e.g. `Closes #233`)._

- Closes #2136

### Screen Recording

_If possible provide a screen recording of proposed change._

https://github.com/webb-tools/webb-dapp/assets/69841784/23f9e8db-c54c-4e24-8921-e6ab077ebcc9

---

### Code Checklist

_Please be sure to add .stories documentation if any additions are made to `libs/webb-ui-components`._

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2024-04-17 07:05 UTC, vutuanlinh2k2 commented
The current number of nominations between the `Nomination` page and `Validator Detail` page is different because it is calculated all the eras in the `Nomination` page while only the current era in the `Validator Details` page. 

The correct way is to show the total in the current era only on the `Nomination` page. 

@yurixander is handling this in his current PR

2024-04-17 17:34 UTC, yurixander requested changes

2024-04-17 17:34 UTC, yurixander commented on apps/tangle-dapp/data/restaking/useRestakingProfile.ts
> +            )
`+` will coerse the value into a Number? What if that number is too large, it won't throw an error? Maybe using `Number()` is clearer than `+` which may not be familiar to most devs

2024-04-17 17:34 UTC, yurixander commented on apps/tangle-dapp/data/restaking/useRestakingProfile.ts
> +          : ledgerOpt.unwrap().total.toNumber()
I think this may fail if the value is too big, instead it should be kept & dealt with as a BN

2024-04-18 05:35 UTC, yurixander approved these changes

2024-04-18 06:33 UTC, vutuanlinh2k2 commented
CI failed due to the Git Commit [link](https://www.conventionalcommits.org/en/v1.0.0/) in Contribution.md is marked unsafe

2024-04-18 09:21 UTC, monaiuu requested changes
Inconsistent `Details` link buttons between tables, let's use the second image link button style for consistency:

<img width="310" alt="Screenshot 2024-04-18 at 4 19 42 PM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/f51cd066-43c6-419b-81b0-f07fa9ac0cec">
<img width="349" alt="Screenshot 2024-04-18 at 4 19 33 PM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/0f027179-5b3e-40a7-acb0-3482c6f6a791">

2024-04-18 14:09 UTC, vutuanlinh2k2 commented
> Inconsistent `Details` link buttons between tables, let's use the second image link button style for consistency:
> 
> <img alt="Screenshot 2024-04-18 at 4 19 42 PM" width="310" src="https://private-user-images.githubusercontent.com/109539270/323543757-f51cd066-43c6-419b-81b0-f07fa9ac0cec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0NDk2NDYsIm5iZiI6MTcxMzQ0OTM0NiwicGF0aCI6Ii8xMDk1MzkyNzAvMzIzNTQzNzU3LWY1MWNkMDY2LTQzYzYtNDE5Yi04MWIwLWYwN2ZhOWFjMGNlYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOFQxNDA5MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZGQ0YTU0ODdhMWM3MjNmNWRjNDU3OWUxNTYxNWY2MWIyZGMwZjg0YzMzOGExZDVlZDQzZjAxMmEzYzBlMDBmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Hz-b1Fsr_0HMGJ0FIJLIzkgfuBftU-38b7bsEXIA-pU"> <img alt="Screenshot 2024-04-18 at 4 19 33 PM" width="349" src="https://private-user-images.githubusercontent.com/109539270/323543818-0f027179-5b3e-40a7-acb0-3482c6f6a791.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0NDk2NDYsIm5iZiI6MTcxMzQ0OTM0NiwicGF0aCI6Ii8xMDk1MzkyNzAvMzIzNTQzODE4LTBmMDI3MTc5LTViM2UtNDBhNy1hY2IwLTM0ODJjNmY2YTc5MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOFQxNDA5MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOTA0MTBjZTI2MTU0YTBiZjBiOTI3NTkxM2Q3Y2Y0OWQ4YzQ2NDRjZmRkNGYxOWQyMjg0OTdlZjg1OGJmYjU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.24WE4aAZ3uUS1F4rGy3H3kwIudDld1hYBDIXvReqFvQ">

Updated!
![CleanShot 2024-04-18 at 21 07 10@2x](https://github.com/webb-tools/webb-dapp/assets/69841784/fd036845-c92f-4c24-bf45-54dc85245e03)

2024-04-18 14:23 UTC, monaiuu approved these changes

2024-04-18 14:33 UTC, AtelyPham approved these changes

2024-04-18 14:50 UTC, merged