feat(tangle-dapp): Add sorting functionalities to tables on Nomination Page
webb-tools/webb-dapp pull request #2424
Opened 2024-07-09 14:31 UTC by vutuanlinh2k2

## Summary of changes

_Provide a detailed description of proposed changes._

- Add sorting functionalities to the Nominations, Payouts, and Validators table
- Update the column align of those tables for better UI

### Proposed area of change

_Put an `x` in the boxes that apply._

- [ ] `apps/bridge-dapp`
- [ ] `apps/hubble-stats`
- [ ] `apps/stats-dapp`
- [x] `apps/tangle-dapp`
- [ ] `apps/testnet-leaderboard`
- [ ] `apps/faucet`
- [ ] `apps/zk-explorer`
- [ ] `libs/webb-ui-components`

### Reference issue to close (if applicable)

_Specify any issues that can be closed from these changes (e.g. `Closes #233`)._

- Closes #2369 

### Screen Recording

_If possible provide a screen recording of proposed change._

https://github.com/webb-tools/webb-dapp/assets/69841784/e335b73f-f0a7-4176-b352-66b4bec6a3d2

---

### Code Checklist

_Please be sure to add .stories documentation if any additions are made to `libs/webb-ui-components`._

- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

2024-07-09 14:42 UTC, drewstone commented
Check link checker

2024-07-09 14:44 UTC, AtelyPham approved these changes
The CI is failing for @vutuanlinh2k2, otherwise looking good!👍

2024-07-09 16:36 UTC, monaiuu approved these changes
LGTM!

Btw, here's a related task for sorting functionality, which would be good to fix: https://github.com/webb-tools/webb-dapp/issues/2378

2024-07-09 20:02 UTC, yurixander approved these changes

2024-07-10 08:41 UTC, saadjhk requested changes

2024-07-10 08:41 UTC, saadjhk commented on package.json
> +    "@buildwithsygma/sygma-sdk-core": "^2.11.0",
`v2.11.0` is faulty, reverting to `2.10.0` should be fine

2024-07-10 17:19 UTC, merged