feat(tangle-dapp): Add Blueprint Overview Page on Tangle dApp
webb-tools/webb-dapp pull request #2494
Opened 2024-08-01 14:57 UTC by vutuanlinh2k2

## Summary of changes

_Provide a detailed description of proposed changes._

- Add Blueprint Overview Page on Tangle dApp

### Proposed area of change

_Put an `x` in the boxes that apply._

- [ ] `apps/bridge-dapp`
- [ ] `apps/hubble-stats`
- [ ] `apps/stats-dapp`
- [x] `apps/tangle-dapp`
- [ ] `apps/testnet-leaderboard`
- [ ] `apps/faucet`
- [ ] `apps/zk-explorer`
- [ ] `libs/webb-ui-components`

### Reference issue to close (if applicable)

_Specify any issues that can be closed from these changes (e.g. `Closes #233`)._

- Closes #2464 

### Screen Recording

_If possible provide a screen recording of proposed change._

#### Light Theme
https://github.com/user-attachments/assets/a3dd9896-3761-43f3-9049-6e36e7ce28a4

#### Dark Theme
https://github.com/user-attachments/assets/4293a1c2-23f9-46d1-b2e2-4e817dd8be2a

---

### Code Checklist

_Please be sure to add .stories documentation if any additions are made to `libs/webb-ui-components`._

- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

2024-08-02 04:36 UTC, monaiuu requested changes
### Blueprint Cards:
- [ ] Implement hover states to blueprint card components (notice color change in description texts & addition of grid image overlay in hover), grid svgs can be exported [here](https://www.figma.com/design/gjR270TYEOiOwOu7IGrivp/%F0%9F%8C%90--Blueprints?node-id=71-9113&t=kooW7WuzJ4oDXPBB-1)
<img width="897" alt="Screenshot 2024-08-02 at 10 51 41 AM" src="https://github.com/user-attachments/assets/990827f2-2427-47c0-b124-0cc48eed2376"> (left is default, right is hover)

- [ ] For boosted cards, update border fill as linear-gradient shown below:
<img width="470" alt="Screenshot 2024-08-02 at 10 43 39 AM" src="https://github.com/user-attachments/assets/830b97e3-71a3-455e-8357-2e469fd0f8d8">
<img width="221" alt="Screenshot 2024-08-02 at 10 44 38 AM" src="https://github.com/user-attachments/assets/1d73f70c-4c0f-483f-b6fb-027e2bd6c5a2">
<img width="644" alt="Screenshot 2024-08-02 at 10 45 15 AM" src="https://github.com/user-attachments/assets/99a1c94a-2a64-4afd-bd4f-48ba854f718f">
<img width="399" alt="Screenshot 2024-08-02 at 10 57 47 AM" src="https://github.com/user-attachments/assets/31f3de84-e8eb-4548-9758-7fceba6ab664">
<img width="656" alt="Screenshot 2024-08-02 at 10 57 24 AM" src="https://github.com/user-attachments/assets/a32d4855-6f8a-44f9-b1b1-7d1df9e272f0">


- [ ] Implement 1-line constraint for Blueprint title, with additional texts truncated
<img width="396" alt="Screenshot 2024-08-02 at 10 55 28 AM" src="https://github.com/user-attachments/assets/d3819f4f-e195-4fc6-9269-6095a3f58b40">

- [ ] Add subtle glow effect to 'boosted' chips; add #fff fill at 1% opacity, with inner shadow indicated below:
<img width="413" alt="Screenshot 2024-08-02 at 11 26 40 AM" src="https://github.com/user-attachments/assets/4d92234d-5623-4d65-b76f-d1ccdb15f993">
<img width="269" alt="Screenshot 2024-08-02 at 11 29 05 AM" src="https://github.com/user-attachments/assets/9998be2f-1a64-48e7-a495-7b5f5ef5f060">
<img width="256" alt="Screenshot 2024-08-02 at 11 35 22 AM" src="https://github.com/user-attachments/assets/db53cc93-af96-4296-ade7-8d7b170fc9c8">
<img width="267" alt="Screenshot 2024-08-02 at 11 35 38 AM" src="https://github.com/user-attachments/assets/3fd5c610-e047-4d05-a5cb-31bc8284dca2">

- [ ] For improved visibility in light mode, reverse gradient effect:
Previous: `background: linear-gradient(180deg, rgba(236, 239, 255, 0.20)0%, rgba(184, 196, 255, 0.20)100%), linear-gradient(180deg, rgba(255, 255, 255, 0.50)0%, rgba(255, 255, 255, 0.30)100%);`
Updated: `background: linear-gradient(180deg, rgba(184, 196, 255, 0.20)0%, rgba(236, 239, 255, 0.20)100%), linear-gradient(180deg, rgba(255, 255, 255, 0.50)0%, rgba(255, 255, 255, 0.30)100%);`
<img width="327" alt="Screenshot 2024-08-02 at 12 00 47 PM" src="https://github.com/user-attachments/assets/f93598d2-4c8b-4ac9-a7fe-f70193be5e9e">

2024-08-02 06:16 UTC, yurixander approved these changes

2024-08-06 10:27 UTC, vutuanlinh2k2 commented
> * linear-gradient(180deg, rgba(236, 239, 255, 0.20)0%, rgba(184, 196, 255, 0.20)100%), linear-gradient(180deg, rgba(255, 255, 255, 0.50)0%, rgba(255, 255, 255, 0.30)100%)

Updated:

https://github.com/user-attachments/assets/130cb1cb-1195-4ab1-971e-40d54b4079d6

2024-08-09 18:09 UTC, monaiuu approved these changes
LGTM!

2024-08-10 01:39 UTC, merged