Restoring UI
webb-tools/webb-dapp pull request #27
Opened 2021-02-12 00:13 UTC by AhmedKorim

Some changes weren't merged, they are added to this PR

1. Deposite/Mixer UI
2. Theme switching

The Mixer isn't initialized

2021-02-12 08:09 UTC, shekohex reviewed
Looks good, just a small changes and this is ready to go!

2021-02-12 08:09 UTC, shekohex commented on README.md
> +    "@webb-tools/mixer-client": "^0.0.6"
Update the version:

```suggestion
    "@webb-tools/mixer-client": "^0.0.7"
```

2021-02-12 16:58 UTC, shekohex approved these changes

2021-02-12 19:03 UTC, drewstone requested changes
Mixer language should be used instead of Swap, and some styling should be fixed (including line breaks / linting that are complaining. Looks good otherwise!

2021-02-12 19:03 UTC, drewstone commented on package.json
> +	"@webb-tools/api": "^0.1.2-33",
Spacing is off

2021-02-12 19:03 UTC, drewstone commented on packages/page-mixer/src/index.tsx
> +export default PageSwap;
Mixer should be used instead of Swap

2021-02-12 19:03 UTC, drewstone commented on packages/page-mixer/src/index.tsx
> +const PageSwap: FC = () => {
Mixer should be used instead of Swap

2021-02-12 19:03 UTC, drewstone commented on packages/page-mixer/src/index.tsx
> +type SwapTabType = 'deposit' | 'withdraw';
Mixer instead of Swap

2021-02-15 12:56 UTC, AhmedKorim commented
@drewstone  I thought this is merged already, You can merge it now to have the app running.
I will add more fixes on functionality and structure on the next PR

2021-02-15 12:57 UTC, merged