Add tooltip for copy address button
webb-tools/webb-dapp pull request #407
Opened 2022-06-02 11:29 UTC by AtelyPham

- feat: add copyable hook for reusable
- feat: add tooltip for copy address button

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

<img width="489" alt="CleanShot 2022-06-02 at 18 27 04@2x" src="https://user-images.githubusercontent.com/60747384/171619570-cd6d4ca3-8106-455f-b8af-1abf1c8209dd.png">

Issue Number: [370](https://github.com/webb-tools/webb-dapp/issues/370).

## What is the new behavior?

<img width="499" alt="CleanShot 2022-06-02 at 18 11 33@2x" src="https://user-images.githubusercontent.com/60747384/171619149-0e81e7c7-bd31-42f4-8dfb-82d25c65c1cb.png">

<img width="497" alt="Screen Shot 2022-06-02 at 18 12 07" src="https://user-images.githubusercontent.com/60747384/171619202-b1326cef-d2ad-4eb1-bc77-6583640b510b.png">

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information

Thank you @dutterbutter for the comprehensive description in the [issue](https://github.com/webb-tools/webb-dapp/issues/370) 😇.

2022-06-02 14:08 UTC, AtelyPham commented
I think that would be fine. Let me update it! You want to use only the `copy-to-clipboard` dependency and remove `react-copy-to-clipboard`, right?

2022-06-02 18:32 UTC, AtelyPham commented
Filter `NaN` values.

Before             |  After
:-------------------------:|:-------------------------:
<img width="518" alt="CleanShot 2022-06-03 at 00 12 28@2x" src="https://user-images.githubusercontent.com/60747384/171701249-ef0237e3-96c1-48dc-af12-2ce08a878582.png"> | <img width="516" alt="CleanShot 2022-06-03 at 00 24 32@2x" src="https://user-images.githubusercontent.com/60747384/171701284-df744108-848c-41aa-9c1d-a922e5fc165a.png">

2022-06-03 11:00 UTC, nepoche reviewed
Looks great! Just requesting one more change to dependencies but other than that it is good to merge.

2022-06-03 11:00 UTC, nepoche commented on yarn.lock
> +react-copy-to-clipboard@^5.0.4:
Can we remove the unused `@polkadot/react-identicon` dependency as well? That way this react-copy-to-clipboard will be removed from our project.

2022-06-03 11:07 UTC, nepoche commented on packages/react-hooks/src/useCopyable.ts
> + * @param {number} deplay The deplay time to reset time copy state in milisecond (default 3000)
```suggestion
 * @param {number} display - The display time to reset time copy state in milliseconds (default 3000)
```

2022-06-03 11:07 UTC, nepoche commented on packages/react-hooks/src/useCopyable.ts
> +export const useCopyable = (deplay: number = 3000) => {
```suggestion
export const useCopyable = (display: number = 3000) => {
```

2022-06-03 11:07 UTC, nepoche commented on packages/react-hooks/src/useCopyable.ts
> +    const timeoutObj = setTimeout(() => setIsCopied(false), deplay);
```suggestion
    const timeoutObj = setTimeout(() => setIsCopied(false), display);
```

2022-06-03 11:23 UTC, AtelyPham commented on packages/react-hooks/src/useCopyable.ts
> +    const timeoutObj = setTimeout(() => setIsCopied(false), deplay);
Updated

2022-06-03 11:23 UTC, AtelyPham commented on packages/react-hooks/src/useCopyable.ts
> +export const useCopyable = (deplay: number = 3000) => {
Updated

2022-06-03 11:24 UTC, AtelyPham commented on packages/react-hooks/src/useCopyable.ts
> + * @param {number} deplay The deplay time to reset time copy state in milisecond (default 3000)
Updated

2022-06-03 11:25 UTC, AtelyPham commented
Updated, thanks for @nepoche 's review 💟 Really appreciated it.

2022-06-03 11:36 UTC, nepoche approved these changes

2022-06-03 14:58 UTC, dutterbutter requested changes

2022-06-03 14:58 UTC, dutterbutter commented on packages/bridge/src/components/DepositConfirm/DepositConfirm.tsx
> +                <Tooltip title={isCopied ? `Copied` : `Copy note the clipboard`}>
`Copy to clipboard`

2022-06-03 15:03 UTC, dutterbutter commented on packages/mixer/src/components/DepositConfirm/DepositConfirm.tsx
> +                <Tooltip title={isCopied ? `Copied` : `Copy note the clipboard`}>
`Copy to clipboard`

2022-06-03 16:44 UTC, merged