Mockup UI for DKG/Eggnet Statistics Page
webb-tools/webb-dapp pull request #447
Opened 2022-06-23 12:27 UTC by AtelyPham

- feat: add the dkg/eggnet statistics tab
- feat: add statistics overview section
- feat: add dkg signers table
- feat: add chart section
- chore: add label color for statistic card
- feat: add progress bar for uptime value
- chore: update width of child tab on sidebar and add border for header button on dark mode

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [x] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?
We don't have the statistic tab on the sidebar and no existing statistics for DKG/Eggnet.

Issue Number: https://github.com/webb-tools/webb-dapp/issues/434

## What is the new behavior?

https://user-images.githubusercontent.com/60747384/175298145-00f9a843-71fa-4b8e-8ba3-be7e084c85f1.mp4

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information
Data on the page is seeding randomly. Need to implement the API query to get real data.

2022-06-23 15:26 UTC, AhmedKorim requested changes
Great job @AtelyPham 🔥

2022-06-23 15:26 UTC, AhmedKorim commented on packages/page-statistics/src/DKGEggnetStatistics/useDKGEggnetStats.ts
> +} as DKGEggnetData;
```suggestion
const initialState: DKGEggnetData = {
  blockNumber: 0,
  signatureThreshold: 0,
  keygenThreshold: 0,
  authorities: 0,
  proposerCount: 0,
  signedProposals: 0,
  unsignedProposalQueue: 0,
  dkgSigners: [],
};
```

2022-06-23 15:26 UTC, AhmedKorim commented on packages/page-statistics/src/DKGEggnetStatistics/useDKGEggnetStats.ts
> +  // const [error, setError] = useState<Error | null | boolean>(null);
Can we remove the comment, if no need for future use?

2022-06-23 15:26 UTC, AhmedKorim commented on packages/page-statistics/src/index.tsx
>  const PageStatistics: FC<StatisticsPageProps> = ({ view }) => {
Can we use switch here for clarity, and ts would till if there is unhandled branch

2022-06-23 16:33 UTC, AtelyPham commented
New UI update

https://user-images.githubusercontent.com/60747384/175349606-bf597036-e571-4d5a-bfe1-2f354d4e6a03.mp4

2022-06-24 10:46 UTC, AhmedKorim approved these changes

2022-07-01 13:20 UTC, merged