Governance Page UI
webb-tools/webb-dapp pull request #457
Opened 2022-07-05 20:30 UTC by AtelyPham

- feat: update new tabs deisgn
- style: mixer page to match new tab design
- style: bridge page to match new tab design
- style: vbridge page to match new tab design
- style: rounded tab
- style: wrap/unwrap page to match new tab design
- refactor: applied className for tab icon
- feat: governance package and tab on side bar
- feat: add proposal card component
- feat: list proposal and pagination setup
- feat: setup pagination and loading state
- chore: center title and update height of loading component for consistent UI

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

Currently, we don't have the governance page.

Issue Number: https://github.com/webb-tools/webb-dapp/issues/308

## What is the new behavior?

I have implemented the Governance Page UI (demo below). But currently, we are using mockup data for display information.

https://user-images.githubusercontent.com/60747384/177410791-53e898c6-4e76-417e-a6aa-34c43862ed1e.mp4

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information
Currently, I'm using the `TablePagination` component from `material-ui/core v4`, we need to migrate `v5` to use the `Pagination` component.

2022-07-05 21:58 UTC, dutterbutter requested changes
Looks great so far @AtelyPham !!

2022-07-05 21:58 UTC, dutterbutter commented on packages/react-hooks/src/useCountDown.ts
> + * @returns an object contains `days`, `hours`, `minutes`, `seconds` and `isExpired` caculate from `targetDate`
```suggestion
 * @param targetDate: Represents the target date to count down from
 * @returns an object containing `days`, `hours`, `minutes`, `seconds` and `isExpired` calculated from `targetDate`
```

2022-07-05 21:58 UTC, dutterbutter commented on packages/react-hooks/src/useCountDown.ts
> +   * @returns the value with leading `0` if value less than `10`
```suggestion
   * @param value: Represents the value to check for adding the leading `0`
   * @returns the value with leading `0` if value is less than `10`
```

2022-07-05 21:58 UTC, dutterbutter commented on packages/react-hooks/src/useCountDown.ts
> + * @returns an object contains `days`, `hours`, `minutes`, `seconds` and `isExpired` caculate from `targetDate`
```suggestion
 * @param countDown: Represents the count down value to calculate time left
 * @returns an object containing `days`, `hours`, `minutes`, `seconds` and `isExpired` calculated from `targetDate`
```

2022-07-08 13:52 UTC, dutterbutter commented
Can you increase the spacing between results and pagination. 

![Screen Shot 2022-07-08 at 8 51 23 AM](https://user-images.githubusercontent.com/29983536/178005348-67d05e66-3f3b-467e-b88e-fbed558f09fc.png)

2022-07-08 22:59 UTC, dutterbutter approved these changes

2022-07-10 22:27 UTC, nepoche approved these changes
Looks great!

2022-07-10 22:38 UTC, merged