Integrate WeareTalisman wallet into the dApp
webb-tools/webb-dapp pull request #497
Opened 2022-08-16 12:42 UTC by AtelyPham

## Summary of changes
- I have integrated the WeareTalisman wallet into the dApp.

### Reference issue to close (if applicable)
- Closes 

-----
### Code Checklist 

- [ ] Tested
- [ ] Documented

2022-08-18 17:10 UTC, dutterbutter commented
@AtelyPham what is remaining for this PR to be ready for review.

2022-08-18 19:52 UTC, AtelyPham commented
I wasn't able to test my environment because Ahmed’s PR added new currencies on the dApp.

He also added a new script in `webb.js` to setup the local environment.

I will test it again and then mark this PR ready for review

2022-08-22 11:46 UTC, AhmedKorim requested changes

2022-08-22 11:46 UTC, AhmedKorim commented on packages/api-providers/src/ext-providers/polkadot/polkadot-provider.ts
> +          throw new Error('Unknown wallet');
Can we have a typed error here   **EX** `throw WebbError.from(WebbErrorCodes.UnkownWallet)`

2022-08-22 11:46 UTC, AhmedKorim commented on packages/react-environment/src/error/interactive-errors/extension-not-installed.tsx
> +      throw new Error('Unknown wallet');
Same here use typed WebbError

2022-08-22 14:29 UTC, AhmedKorim approved these changes
LGTM!

2022-08-22 14:30 UTC, merged