Register accounts on deposit and enable registration with MetaMask.
webb-tools/webb-dapp pull request #500
Opened 2022-08-18 13:14 UTC by nepoche

## Summary of changes
- Require a NoteAccount to complete the Deposit flow on the DApp.
- Enable a button for 'Connecting With Metamask'.

### Reference issue to close (if applicable)

-----
### Code Checklist 

- [x] Tested
- [ ] Documented

2022-08-18 17:53 UTC, dutterbutter commented
@nepoche I seem to be running into an issue regarding loading notes from the account manager. To reproduce:
1. Create a note account
2. Paste a note into the load note input box 
3. The page then sends me to the following:
<img width="445" alt="Screen Shot 2022-08-18 at 12 33 07 PM" src="https://user-images.githubusercontent.com/29983536/185461685-52b2763a-35d7-498f-9e7e-13e3007ae12e.png">

Furthermore, if I reload the UI and select the note account manager I am redirected back to the above error message page.

2022-08-18 18:26 UTC, dutterbutter commented
> @nepoche I seem to be running into an issue regarding loading notes from the account manager. To reproduce:
> 
> 1. Create a note account
> 2. Paste a note into the load note input box
> 3. The page then sends me to the following:
> 
> <img alt="Screen Shot 2022-08-18 at 12 33 07 PM" width="445" src="https://user-images.githubusercontent.com/29983536/185461685-52b2763a-35d7-498f-9e7e-13e3007ae12e.png">
> 
> Furthermore, if I reload the UI and select the note account manager I am redirected back to the above error message page.

**Update:** It seems it broke using a very old note, new notes generated works fine.

2022-08-18 22:11 UTC, AhmedKorim approved these changes
LGTM!

2022-08-19 05:45 UTC, drewstone commented
@AhmedKorim I can't tell if you ran into the issues @dutterbutter is facing but it would be good to QA these PRs certainly when others are facing issues. LGTM is not enough here.

2022-08-19 05:54 UTC, drewstone approved these changes
LGTM, just small renaming thought, feel free to shut down if you think it's better named as is.

2022-08-19 05:54 UTC, drewstone commented on packages/api-providers/src/web3/vanchor-registration.ts
> +  async isPairingRegistered(anchorAddress: string, account: string, pubkey: string): Promise<boolean> {
I would consider renaming to `isPairRegistered`

2022-08-19 05:55 UTC, drewstone requested changes
Code looks good, let's do more thorough QA to ensure @dutterbutter's issues are resolved.

2022-08-19 13:10 UTC, dutterbutter commented
It looks like my issue has been resolved, as I am unable to reproduce now.

2022-08-19 14:35 UTC, merged