Setup packages
webb-tools/webb-dapp pull request #542
Opened 2022-09-02 20:38 UTC by AhmedKorim

## Summary of changes
- 

### Reference issue to close (if applicable)
- Closes 

-----
### Code Checklist 

- [ ] Tested
- [ ] Documented

2022-09-08 14:53 UTC, AtelyPham commented on package.json
> +    "@graphql-codegen/typescript-react-apollo": "3.3.3",
Some plugins you have commented out in the plugins section of the `codegen.yml` file, can we remove any unused dependencies here?

2022-09-09 13:25 UTC, nepoche requested changes

2022-09-09 13:25 UTC, nepoche commented on packages/api-providers/src/contracts/wrappers/webb-vanchor.ts
> +import { BytesLike } from '@ethersproject/bytes';
```suggestion
```

2022-09-09 13:25 UTC, nepoche commented on packages/api-providers/src/polkadot/vanchor-deposit.ts
> +        token: '1',
The `extData` value should be consistent with the value in the `ProvingManagerSetupInput`. I would suggest a change to both for something like:

extData - wrappableAssetRaw.toString() ?? '0'
provingInput - hexToU8a(wrappableAssetRaw.toString()) ?? Uint8Array.from([0])

2022-09-09 13:25 UTC, nepoche commented on packages/api-providers/src/polkadot/vanchor-withdraw.ts
> +            token: u8aToHex(Uint8Array.from([0])),
```suggestion
            token: '0',
```

2022-09-09 13:25 UTC, nepoche commented on packages/page-governance/src/ProposalDetail/VotersTable/VotersTable.tsx
> +const Grid = _Grid as any;
Please add a comment as to why this is how we are importing from 'gridjs-react'

2022-09-09 13:34 UTC, nepoche approved these changes

2022-09-09 13:38 UTC, merged