Implemented Filters for proposers and authorities tables
webb-tools/webb-dapp pull request #646
Opened 2022-10-13 11:18 UTC by AhmedKorim

## Summary of changes
 

### Reference issue to close (if applicable)
- Closes #630 
- Closes #631 
-----
### Code Checklist 

- [ ] Tested
- [ ] Documented

2022-10-13 15:47 UTC, dutterbutter commented on packages/page-statistics/src/containers/AuthoritiesTable/AuthoritiesTable.tsx
> +  console.log({ authorities });
Please remove the console log here.

2022-10-17 19:54 UTC, dutterbutter requested changes
Can you please remove the `console.log` that is polluting the console:
```
Active session 134
134
```

Also it seems something has changed in this pr as I am receiving a 404 from backend yet the backend seems to working fine.

2022-10-17 20:24 UTC, AhmedKorim commented
@dutterbutter  there is a PR on SubQuery side that need to be deployed

2022-10-17 20:32 UTC, dutterbutter commented
> @dutterbutter there is a PR on SubQuery side that need to be deployed

done. @AhmedKorim

2022-10-17 20:35 UTC, dutterbutter commented
@AhmedKorim deployed updated backend resolved the 400 resource issue. If you could please remove the following console logs:
<img width="302" alt="Screen Shot 2022-10-17 at 3 34 15 PM" src="https://user-images.githubusercontent.com/29983536/196277898-eede492f-790a-49dd-8042-c3046c05d617.png">
<img width="250" alt="Screen Shot 2022-10-17 at 3 34 18 PM" src="https://user-images.githubusercontent.com/29983536/196277901-bdabd120-5af1-43ed-aaa1-56a53213b07f.png">

2022-10-17 22:37 UTC, dutterbutter approved these changes

2022-10-17 22:37 UTC, merged