Update authority location and  handle unkown authority locations
webb-tools/webb-dapp pull request #701
Opened 2022-11-21 14:03 UTC by AhmedKorim

## Summary of changes
- Fetch the authority location from the account entity
- Added a fallback `anonymous` label for the unset location

### Reference issue to close (if applicable)
- Closes 

-----
### Code Checklist 

- [ ] Tested
- [ ] Documented

2022-11-21 14:34 UTC, AtelyPham commented on apps/stats-dapp/src/containers/AuthoritiesTable/AuthoritiesTable.tsx
> +          {uniCode ? getUnicodeFlagIcon(uniCode) : 'Anonymous'}
The fallback should be `Unknown` instead of `Anonymous` as the issue https://github.com/webb-tools/webb-dapp/issues/685 has described.

2022-11-21 14:36 UTC, AtelyPham requested changes
Correct the fallback value please, otherwise all looks good to me 👍.

2022-11-21 16:29 UTC, dutterbutter commented
I get a crash on selecting auth details 

![Screen Shot 2022-11-21 at 10 28 51 AM](https://user-images.githubusercontent.com/29983536/203108087-9a424b89-34b7-433a-aeab-e91290584bc0.png)

2022-11-23 14:18 UTC, dutterbutter commented
Couple small things @AhmedKorim. It doesn't seem the links are enabled, even tho the twitter, and website of the authority is set. The other it seems there is a green dot above the flag icon.

**Links disabled:**
![Screen Shot 2022-11-23 at 8 05 53 AM](https://user-images.githubusercontent.com/29983536/203568713-4abd3c8f-f515-4f3a-9510-b26950a27a20.png)

**Green dot:**
![Screen Shot 2022-11-23 at 8 05 56 AM](https://user-images.githubusercontent.com/29983536/203568710-6fa9c22c-8bdf-45fc-9cc4-fdff5c70b88e.png)

2022-11-24 13:51 UTC, dutterbutter commented
Crashes on Authorities detail drawer. 

![Screen Shot 2022-11-24 at 7 50 47 AM](https://user-images.githubusercontent.com/29983536/203800328-fbfd670d-ba2e-43df-8e53-38db279a3832.png)

2022-11-24 14:21 UTC, dutterbutter approved these changes

2022-11-24 14:22 UTC, merged