Fixing The Chain Ring Display & Adding some Improvements
webb-tools/webb-dapp pull request #777
Opened 2022-12-06 16:10 UTC by AtelyPham

## Summary of changes
- Fixing the bug about The ChainsRing component not displaying the icon and label properly in case we only have the destination chain.
- The chain list extends to the bottom of the card.
- Unavailable tokens must be disabled.
- "Try another wallet" should open the connect wallet modal
- The AmountInput only allows number value

### Reference issue to close (if applicable)
- Closes https://github.com/webb-tools/webb-dapp/issues/775
- A part of the issue https://github.com/webb-tools/webb-dapp/issues/749

-----
### Code Checklist 

- [x] Tested
- [x] Documented

2022-12-06 19:39 UTC, dutterbutter commented on apps/bridge-dapp/src/hooks/useTryAnotherWalletWithView.tsx
> +                  'There is not selected wallet in try again function'
```suggestion
                  'There is no wallet selected. Please select a wallet and try again.'
```

2022-12-06 19:40 UTC, dutterbutter requested changes
Small proposed changes.

2022-12-07 08:30 UTC, AtelyPham commented
Add more improvements:

- Consistent all the small all-cap text font size
- Disabled amount inputs (custom and fixed) when token or chain is not selected
- Do not pop up the wallet modal when changing the chain if the selected chain is supported by the current active wallet.

2022-12-07 13:51 UTC, dutterbutter approved these changes
LGTM @AtelyPham ! Since it addresses comments from #749 let's wait to merge to get visual reviews from @seeddisperser or @monaiuu

2022-12-07 13:55 UTC, AhmedKorim approved these changes

2022-12-07 20:54 UTC, seeddisperser commented
One more fix: 

if the user has not connected their wallet, the button at the bottom of the transfer and withdraw tabs should prompt the user to connect their wallet, as implemented in the deposit tab.

2022-12-07 22:42 UTC, merged

2022-12-08 05:15 UTC, AtelyPham commented
Moved remaining items to issue https://github.com/webb-tools/webb-dapp/issues/749.