Removes donut chart and adds stacked area chart
webb-tools/webb-dapp pull request #813
Opened 2022-12-13 13:55 UTC by devpavan04

## Summary of changes
- Removes donut chart and open proposal table from proposals page
- Adds stacked area chart for total proposal count over time

### Reference issue to close (if applicable)
- Closes #812

2022-12-13 14:20 UTC, dutterbutter commented
@devpavan04 can we make 3M the default filter on the chart so it takes up more of the chart space. In addition, can you add hover states on the chart to display the actual count of the proposals? For example, if I hover over Refresh proposal it should display 1. 

Great work!

2022-12-13 14:26 UTC, AtelyPham commented on libs/webb-ui-components/src/components/Chip/types.ts
> +  onClick?: React.EventHandler<React.MouseEvent | React.KeyboardEvent>;
The `onClick` is already inside the `WebbComponentBase` interface. We don't need to redefine it here.

2022-12-13 16:31 UTC, devpavan04 commented
### Changes overview

https://user-images.githubusercontent.com/53374218/207389447-2b62d9df-2e48-4864-9ed3-9329d2225415.mov

2022-12-13 16:51 UTC, AtelyPham commented
Can we add the hover state for legends on the right? When you hover one legend on the right, it will pop-up the count of that proposal. Can you confirm that? @dutterbutter 

Also, update the chart labels color to `text-mono-100`. @devpavan04 

![CleanShot 2022-12-13 at 23 45 14@2x](https://user-images.githubusercontent.com/60747384/207394538-42b9ad74-3702-4c88-a75d-0edc5feb115f.png)

2022-12-13 16:59 UTC, AhmedKorim requested changes
Great job, Just small changes and documentation missing

2022-12-13 16:59 UTC, AhmedKorim commented on apps/stats-dapp/src/gql/proposals.graphql
> +query ProposalsOvertimeTotalCount($start: Int!, $end: Int!) {
Please add comments to describe the parameters

2022-12-13 16:59 UTC, AhmedKorim commented on apps/stats-dapp/src/provider/hooks/useProposals.ts
> +    let _blockRanges: BlockRanges = [];
The `_` before a variable name normally means that the variables isn't in use please remove it

2022-12-13 16:59 UTC, AhmedKorim commented on apps/stats-dapp/src/provider/hooks/useProposals.ts
> +          isLoading: true,
`isLoading` should be `false` here

2022-12-13 16:59 UTC, AhmedKorim commented on apps/stats-dapp/src/provider/hooks/useProposals.ts
> +    )
Before doing the mapping from `parameters` to `query` you should set the state to be `isLoading= true`

2022-12-13 16:59 UTC, AhmedKorim commented on apps/stats-dapp/src/utils/getBlockRanges.ts
> +};
Please add more comments documenting this function

2022-12-14 22:22 UTC, devpavan04 commented
### Changes overview

https://user-images.githubusercontent.com/53374218/207727553-bca943d0-14a5-420e-8fc7-708a4e22456f.mov

2022-12-15 00:36 UTC, dutterbutter approved these changes

2022-12-15 00:36 UTC, merged