Shielded assets table UI fixes
webb-tools/webb-dapp pull request #963
Opened 2023-01-31 18:20 UTC by devpavan04

---
name: Pull request
about: Proposed changes
title: Shielded assets table UI fixes
labels: needs review 👓
assignees: @devpavan04 

---

## Summary of changes
_Provide a detailed description of proposed changes._
- Updates table pagination text
- Replaces available balance with total balance in table column label
- Composition icons in table are now bigger
- Balance is table is now fixed to six decimal places

### Proposed area of change
_Put an `x` in the boxes that apply._

- [x] `apps/bridge-dapp`
- [ ] `apps/stats-dapp`
- [ ] `apps/webbsite`
- [ ] `libs/webb-ui-components`

### Reference issue to close (if applicable)
_Specify any issues that can be closed from these changes (e.g. Closes #233)._
- Closes #943 

### Screen Recording
_If possible provide a screen recording of proposed change._

https://user-images.githubusercontent.com/53374218/215847960-6dc10d88-4d96-4bcc-b860-bae1d99e8dbb.mov

-----
### Code Checklist 
_Please be sure to add .stories documentation if any additions are made to `libs/webb-ui-components`._

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2023-01-31 19:44 UTC, dutterbutter requested changes
Lets just use 'Balance' for table header for both tabs. Can we also centre the items in the table?

2023-01-31 19:44 UTC, dutterbutter commented on apps/bridge-dapp/src/containers/ShieldedAssetsTableContainer/ShieldedAssetsTableContainer.tsx
> +    header: 'Total Balance',
```suggestion
    header: 'Balance',
```

2023-01-31 19:44 UTC, dutterbutter commented on apps/bridge-dapp/src/containers/ShieldedAssetsTableContainer/ShieldedAssetsTableContainer.tsx
> +        title="available assets"
```suggestion
        title="assets"
```

2023-01-31 19:44 UTC, dutterbutter commented on apps/bridge-dapp/src/containers/SpendNotesTableContainer/SpendNotesTableContainer.tsx
> +        title="available notes"
```suggestion
        title="notes"
```

2023-02-01 13:17 UTC, AtelyPham reviewed
LGTM 👍 Please fix the ci failing here @devpavan04

2023-02-01 15:45 UTC, dutterbutter approved these changes

2023-02-01 15:55 UTC, merged